import Banner from "@/component/banner";
import { Box } from "@mui/material";
import Head from "next/head";
import heroImage from "@/banner/hero-banner.jpg";

import ServiceComponent from "@/component/service";
import banner2 from "@/banner/banner-2.jpg";
import Choose from "@/component/home/choose";
import homeAbout from "@/banner/home-about.jpg";
import tomato from "@/banner/tomato-basil.png";
import AboutComponent from "@/component/home/about";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Banner
          img={heroImage.src}
          heading="Where taste meets excellence service."
          description="Vulputate rutrum tempus eleifend faucibus vehicula taciti potenti facilisis ante consectetuer vitae nisl"
          buttonText="Discover More"
          subHeading="Welcome to Infinity Chaat House"
        />
        <Box sx={{ pt: 7 }}>
          <AboutComponent
            img1={homeAbout}
            img2={tomato}
            subHeading="About Us"
            heading="Catering is not just all about food. It’s about excellent service as well"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."
          />
        </Box>
        <Box sx={{ pt: { lg: 15, xs: 5 } }}>
          <ServiceComponent />
        </Box>
        <Box>
          <Banner
            img={banner2.src}
            heading="Discount up to 50% for traditional menu, only this month."
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."
            buttonText="Claim Promo"
          />
        </Box>
        <Box sx={{ pt: 7 }}>
          <Choose />
        </Box>
      </Box>
    </>
  );
}
